spring:
  application:
    name: order
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123123
    url: jdbc:mysql://47.100.108.8:3306/SpringCloud_Sell?characterEncoding=utf-8&useSSL=false
  jpa:
#    show-sql: true
    properties:
      hibernate:
        format_sql: true
        show_sql: true

  redis:
    host: http://47.100.108.8
    port: 6379

  rabbitmq:
    host: http://47.100.108.8
    port: 5672
    username: guest
    password: guest

eureka:
  client:
    service-url:
      defaultZone: localhost:8761/eureka
env: abc

# 修改获取服务的方式, 默认是轮询
# 当前设置的方式为 随机
#PRODUCT:
#  ribbon:
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
