spring:
  application:
    name: product
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123123
    url: jdbc:mysql://47.100.108.8:3306/SpringCloud_Sell?characterEncoding=utf-8&useSSL=false

  rabbitmq:
    host: 47.100.108.8
    port: 5672
    username: guest
    password: guest

  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: true